// apps/backend/src/routes/consumer.passportExtract.test.ts
//
// ══════════════════════════════════════════════════════════════════════
// POST /api/consumer/profile/documents/:id/extract
//
// FOUR CLAIMS, AND THE FIRST TWO ARE THE NON-NEGOTIABLE ONES:
//   1. OWN-SCOPED  — consumer B cannot read consumer A's passport.
//   2. NO PERSIST  — the route writes NOTHING. Not a field, not a status.
//   3. MAPPED      — the ten Applicant fields come back with an honest
//                    provenance tier per field, converted by the SAME
//                    ISO3→ISO2 / century logic the B2B path uses.
//   4. NO 500s     — an unreadable passport is a 422 with a category the
//                    UI can turn into a sentence, never a server error.
// ══════════════════════════════════════════════════════════════════════
//
// WHAT IS REAL HERE, AND WHAT IS NOT.
//
// Real: the router, requireConsumer, consumer tokens, Mongo
// (mongodb-memory-server), the ConsumerDocument rows, the local-disk
// storage driver (services/consumerDocumentStorage.ts — NODE_ENV is
// "test", so activeDriver() returns "local-disk" and the bytes genuinely
// go to and come back from .devdata/), services/consumerPassportExtraction
// .ts, services/extractPassportGemini.ts, utils/mrz.ts, utils/countryCodes
// .ts and utils/passportCrossCheck.ts.
//
// Mocked: @google/genai, and only that. It is the network boundary, not
// the thing under test — the same line services/extractPassportGemini
// .test.ts already draws. Everything between the HTTP request and that
// boundary runs for real, which is the point: this proves the engine is
// actually reusable from the consumer path, rather than proving that a
// stub returns what the stub was told to return.
import { describe, it, expect, beforeAll, afterAll, beforeEach, vi } from "vitest";
import express from "express";
import cookieParser from "cookie-parser";
import request from "supertest";
import mongoose from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";
import { rm } from "node:fs/promises";
import path from "node:path";

// Secrets must exist BEFORE any import that reads them — identical
// preamble to consumer.profile.test.ts.
process.env.JWT_SECRET = "b2b-jwt-secret-for-tests";
process.env.CONSUMER_JWT_SECRET = "consumer-jwt-secret-for-tests";
process.env.NODE_ENV = "test";
process.env.MONGO_URI ||= "mongodb://127.0.0.1:27017/consumer-passport-extract-test";
process.env.FRONTEND_ORIGIN ||= "http://localhost:5173";
process.env.S3_BUCKET ||= "test-bucket";
process.env.GEMINI_API_KEY ||= "test-gemini-key";

const { generateContentMock } = vi.hoisted(() => ({ generateContentMock: vi.fn() }));

vi.mock("@google/genai", () => {
  class ApiError extends Error {
    status: number;
    constructor({ message, status }: { message: string; status: number }) {
      super(message);
      this.name = "ApiError";
      this.status = status;
    }
  }
  return {
    GoogleGenAI: vi.fn().mockImplementation(() => ({
      models: { generateContent: (...args: any[]) => generateContentMock(...args) },
    })),
    ApiError,
    Type: { OBJECT: "OBJECT", STRING: "STRING", BOOLEAN: "BOOLEAN", ARRAY: "ARRAY", NUMBER: "NUMBER" },
  };
});

const { default: Consumer } = await import("../models/Consumer.js");
const { default: ConsumerProfile } = await import("../models/ConsumerProfile.js");
const { default: ConsumerDocument } = await import("../models/ConsumerDocument.js");
const { default: consumerProfileRouter } = await import("./consumer.profile.js");
const { signConsumerAccessToken } = await import("../utils/consumerJwt.js");
const { putConsumerDocument, CONSUMER_DOCUMENT_LOCAL_ROOT } = await import(
  "../services/consumerDocumentStorage.js"
);

const app = express();
app.use(express.json());
app.use(cookieParser());
app.use("/api/consumer/profile", consumerProfileRouter);

let mongod: MongoMemoryServer;
const createdConsumerIds: string[] = [];

/* ── THE FIXTURE ──────────────────────────────────────────────────────
 * A structurally valid TD3 machine-readable zone for a fictional Indian
 * passport. Every check digit is correct, so the deterministic parser
 * accepts it and deriveConfidence returns "high" — which is what lets the
 * provenance assertions below distinguish VERIFIED from MACHINE_READ
 * rather than everything collapsing into a failure.
 *
 * Written out as LITERALS rather than computed by calling this repo's own
 * computeCheckDigit at test time: a fixture generated by the code under
 * test proves only that the code agrees with itself. These digits were
 * computed once, out-of-band, from the ICAO 9303 7-3-1 rule.
 *
 * The values are chosen to exercise both converters at once:
 *   - "IND"    -> normaliseToIso2 -> "IN"     (ISO3→ISO2)
 *   - "900411" -> resolveMrzDate("dob")    -> "1990-04-11"
 *                 The dob rule specifically: 2090 would be in the future,
 *                 so it falls back a century. A naive 2000+YY gives 2090.
 *   - "300815" -> resolveMrzDate("expiry") -> "2030-08-15"
 *                 The expiry rule: ALWAYS this century, no comparison.
 *                 The two rules disagreeing is the whole point of testing
 *                 both — 30 resolves forward here and 90 resolves back.
 */
const MRZ_LINE1_CONTENT = "P<INDSHARMA<<PRIYA<ANITA";
const MRZ_LINE2 = "Z1234567<1IND9004115F3008155<<<<<<<<<<<<<<08";

function geminiReply(overrides: Record<string, any> = {}) {
  return {
    text: JSON.stringify({
      mrz_found: true,
      line1_content: MRZ_LINE1_CONTENT,
      line2: MRZ_LINE2,
      viz_found: false,
      viz: null,
      ...overrides,
    }),
  };
}

async function makeConsumer(email: string) {
  const consumer = await Consumer.create({
    email,
    name: email.split("@")[0],
    passwordHash: "not-used-in-these-tests",
  });
  createdConsumerIds.push(String(consumer._id));
  const token = signConsumerAccessToken({
    consumerId: String(consumer._id),
    tokenVersion: (consumer as any).tokenVersion,
  });
  return { id: String(consumer._id), token };
}

/**
 * A real document row with real bytes behind it, written through the SAME
 * driver the route reads back through. Not a row pointing at nothing: the
 * local-disk path is exactly the incompatibility this feature exists to
 * handle (getObjectBuffer, the B2B path, cannot read it), so a test that
 * skipped the write would skip the one genuinely new line of plumbing.
 */
async function makePassportDoc(consumerId: string, docCode = "PASSPORT_ORIGINAL") {
  const stored = await putConsumerDocument({
    buffer: Buffer.from("not-a-real-jpeg-the-model-is-mocked"),
    mime: "image/jpeg",
    originalName: "passport.jpg",
    consumerId,
  });
  return ConsumerDocument.create({
    consumerId: new mongoose.Types.ObjectId(consumerId),
    workspaceId: new mongoose.Types.ObjectId(),
    category: "IDENTITY",
    docCode,
    driver: stored.driver,
    storageKey: stored.storageKey,
    bucket: stored.bucket,
    originalFilename: "passport.jpg",
    mimeType: "image/jpeg",
    sizeBytes: 35,
  });
}

const auth = (token: string) => ["Authorization", `Bearer ${token}`] as const;

beforeAll(async () => {
  mongod = await MongoMemoryServer.create();
  await mongoose.connect(mongod.getUri(), { dbName: "extract-test" });
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongod.stop();
  // The local driver really wrote files. Clean them up — .devdata is
  // gitignored, so this is tidiness, not safety.
  for (const id of createdConsumerIds) {
    await rm(path.join(CONSUMER_DOCUMENT_LOCAL_ROOT, id), { recursive: true, force: true });
  }
});

beforeEach(async () => {
  generateContentMock.mockReset();
  await Promise.all([
    Consumer.deleteMany({}),
    ConsumerProfile.deleteMany({}),
    ConsumerDocument.deleteMany({}),
  ]);
  createdConsumerIds.length = 0;
});

/* ═══════════════════════════════════════════════════════════════════
 * 1. OWN-SCOPED
 * ═══════════════════════════════════════════════════════════════════ */
describe("POST /documents/:id/extract — ownership", () => {
  it("refuses another consumer's document with 404, and never calls the reader", async () => {
    const alice = await makeConsumer("alice@example.com");
    const mallory = await makeConsumer("mallory@example.com");
    const aliceDoc = await makePassportDoc(alice.id);

    generateContentMock.mockResolvedValue(geminiReply());

    const res = await request(app)
      .post(`/api/consumer/profile/documents/${aliceDoc._id}/extract`)
      .set(...auth(mallory.token));

    expect(res.status).toBe(404);
    expect(res.body.fields).toBeUndefined();
    // The ownership clause is part of the QUERY, so the row is never
    // loaded and the model is never reached. A 404 produced AFTER a
    // Gemini call would still have leaked the read.
    expect(generateContentMock).not.toHaveBeenCalled();
  });

  it("refuses an unauthenticated caller", async () => {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    const res = await request(app).post(`/api/consumer/profile/documents/${doc._id}/extract`);
    expect(res.status).toBe(401);
    expect(generateContentMock).not.toHaveBeenCalled();
  });

  it("takes the consumer from the session, never from the body", async () => {
    const alice = await makeConsumer("alice@example.com");
    const mallory = await makeConsumer("mallory@example.com");
    const aliceDoc = await makePassportDoc(alice.id);
    generateContentMock.mockResolvedValue(geminiReply());

    // Mallory names Alice as the consumer. There is no such parameter, and
    // this asserts that adding one later would not silently start working.
    const res = await request(app)
      .post(`/api/consumer/profile/documents/${aliceDoc._id}/extract`)
      .set(...auth(mallory.token))
      .send({ consumerId: alice.id });

    expect(res.status).toBe(404);
    expect(generateContentMock).not.toHaveBeenCalled();
  });

  it("404s a well-formed id that does not exist, and a malformed one", async () => {
    const alice = await makeConsumer("alice@example.com");
    const missing = await request(app)
      .post(`/api/consumer/profile/documents/${new mongoose.Types.ObjectId()}/extract`)
      .set(...auth(alice.token));
    expect(missing.status).toBe(404);

    const malformed = await request(app)
      .post("/api/consumer/profile/documents/not-an-objectid/extract")
      .set(...auth(alice.token));
    expect(malformed.status).toBe(404);
  });
});

/* ═══════════════════════════════════════════════════════════════════
 * 2. NO PERSIST — the non-negotiable
 * ═══════════════════════════════════════════════════════════════════ */
describe("POST /documents/:id/extract — persists nothing", () => {
  it("leaves the document row byte-identical after a SUCCESSFUL extraction", async () => {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    generateContentMock.mockResolvedValue(geminiReply());

    const before = await ConsumerDocument.findById(doc._id).lean();

    const res = await request(app)
      .post(`/api/consumer/profile/documents/${doc._id}/extract`)
      .set(...auth(alice.token));
    expect(res.status).toBe(200);
    expect(res.body.fields.passportNumber.value).toBe("Z1234567");

    const after = await ConsumerDocument.findById(doc._id).lean();
    // Whole-document equality, not a field-by-field spot check: a
    // spot check only catches the fields somebody thought to name, and
    // the claim being made here is that NOTHING changed. updatedAt is
    // included on purpose — a save would move it even if every value
    // it wrote happened to match.
    expect(after).toEqual(before);
  });

  it("creates no profile, and touches no existing one", async () => {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    generateContentMock.mockResolvedValue(geminiReply());

    // No ConsumerProfile exists yet. The extracted passport number, name
    // and date of birth must not conjure one.
    expect(await ConsumerProfile.countDocuments({})).toBe(0);

    await request(app)
      .post(`/api/consumer/profile/documents/${doc._id}/extract`)
      .set(...auth(alice.token))
      .expect(200);

    expect(await ConsumerProfile.countDocuments({})).toBe(0);
  });

  it("writes nothing to ANY collection — a whole-database census", async () => {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    generateContentMock.mockResolvedValue(geminiReply());

    // The strongest form of the claim available: count every document in
    // every collection before and after. A new row anywhere — an audit
    // log, an activity record, a cache entry, a collection introduced by
    // a future refactor — moves one of these numbers.
    const census = async () => {
      const collections = await mongoose.connection.db.listCollections().toArray();
      const out: Record<string, number> = {};
      for (const c of collections) {
        out[c.name] = await mongoose.connection.db.collection(c.name).countDocuments();
      }
      return out;
    };

    const before = await census();
    await request(app)
      .post(`/api/consumer/profile/documents/${doc._id}/extract`)
      .set(...auth(alice.token))
      .expect(200);
    expect(await census()).toEqual(before);
  });

  it("leaves the document row untouched after a FAILED extraction too", async () => {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    // The B2B twin writes extractionStatus: "FAILED" and an error onto the
    // document here. This route must not — the failure is reported in the
    // response and nowhere else.
    generateContentMock.mockResolvedValue({
      text: JSON.stringify({ mrz_found: false, line1_content: null, line2: null, viz_found: false, viz: null }),
    });

    const before = await ConsumerDocument.findById(doc._id).lean();
    await request(app)
      .post(`/api/consumer/profile/documents/${doc._id}/extract`)
      .set(...auth(alice.token))
      .expect(422);
    expect(await ConsumerDocument.findById(doc._id).lean()).toEqual(before);
  });
});

/* ═══════════════════════════════════════════════════════════════════
 * 3. THE MAPPING AND THE CONVERTERS
 * ═══════════════════════════════════════════════════════════════════ */
describe("POST /documents/:id/extract — field mapping", () => {
  async function extract(overrides: Record<string, any> = {}) {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    generateContentMock.mockResolvedValue(geminiReply(overrides));
    const res = await request(app)
      .post(`/api/consumer/profile/documents/${doc._id}/extract`)
      .set(...auth(alice.token));
    return res;
  }

  it("returns the ten Applicant keys, converted, with honest provenance", async () => {
    const res = await extract();
    expect(res.status).toBe(200);
    expect(res.body.confidence).toBe("high");

    const f = res.body.fields;

    // Every key the Applicant form holds is present in the response,
    // even where the reader has nothing to say (null) — so the client
    // never has to guess whether a missing key means "not extracted" or
    // "this build is older than that field".
    expect(Object.keys(f).sort()).toEqual(
      [
        "dateOfBirth",
        "firstName",
        "gender",
        "lastName",
        "middleName",
        "nationality",
        "passportExpiryDate",
        "passportIssueDate",
        "passportIssuingCountry",
        "passportNumber",
      ].sort(),
    );

    // ── VERIFIED: MRZ fields that carry their own check digit ────────
    expect(f.passportNumber).toEqual({ value: "Z1234567", provenance: "VERIFIED" });
    expect(f.dateOfBirth).toEqual({ value: "1990-04-11", provenance: "VERIFIED" });
    expect(f.passportExpiryDate).toEqual({ value: "2030-08-15", provenance: "VERIFIED" });

    // ── MACHINE_READ: MRZ, but TD3 has no check digit for these ──────
    // They must NOT wear the verified badge — a misread here is
    // undetectable, which is the entire reason the tier exists.
    expect(f.lastName).toEqual({ value: "SHARMA", provenance: "MACHINE_READ" });
    expect(f.nationality).toEqual({ value: "IN", provenance: "MACHINE_READ" });
    expect(f.passportIssuingCountry).toEqual({ value: "IN", provenance: "MACHINE_READ" });
    expect(f.gender).toEqual({ value: "FEMALE", provenance: "MACHINE_READ" });

    // No VIZ was returned, so there is no printed issue date to offer.
    expect(f.passportIssueDate).toBeNull();
    expect(res.body.mismatches).toEqual([]);
    expect(res.body.unconverted).toEqual([]);
  });

  it("converts ISO3 to ISO2 — the country converter", async () => {
    const res = await extract();
    // "IND" on the wire, "IN" in the response. The form's CountryField
    // stores ISO2; handing it "IND" would render an empty select.
    expect(res.body.fields.nationality.value).toBe("IN");
    expect(res.body.fields.passportIssuingCountry.value).toBe("IN");
  });

  it("resolves the MRZ century differently for birth and expiry", async () => {
    const res = await extract();
    // Both are YY=90/30 six-digit MRZ dates. A single shared rule cannot
    // produce both of these answers, which is why resolveMrzDate takes a
    // `kind` — and why this assertion is two lines, not one.
    expect(res.body.fields.dateOfBirth.value).toBe("1990-04-11"); // NOT 2090
    expect(res.body.fields.passportExpiryDate.value).toBe("2030-08-15"); // NOT 1930
  });

  it("gives the WHOLE of givenNames to firstName and never invents a middle name", async () => {
    const res = await extract();
    // The MRZ says "PRIYA ANITA". TD3 has no delimiter that separates a
    // two-word given name from a first-plus-middle, so splitting on the
    // space would be a guess printed into someone's visa application.
    expect(res.body.fields.firstName.value).toBe("PRIYA ANITA");
    // null, NOT "". An empty string would CLEAR a middle name the person
    // had already entered — deleting real data on the strength of a
    // format that cannot represent it.
    expect(res.body.fields.middleName).toBeNull();
  });

  it("flags a field whose own check digit failed, without failing the read", async () => {
    // Same line 2 with the document-number check digit changed 1 -> 9.
    // The document number itself still comes back — the reader can see and
    // correct it — but it is marked as not adding up.
    const badLine2 = "Z1234567<9IND9004115F3008155<<<<<<<<<<<<<<08";
    const res = await extract({ line2: badLine2 });
    expect(res.status).toBe(200);
    expect(res.body.confidence).toBe("low");
    expect(res.body.fields.passportNumber.checkDigitFailed).toBe(true);
    // A field whose OWN digit passed is not tarred by its neighbour.
    expect(res.body.fields.dateOfBirth.checkDigitFailed).toBeUndefined();
  });

  it("reports an unrecognised country instead of silently dropping it", async () => {
    // "UTO" is the ICAO specimen's fictional Utopia. A reader whose
    // nationality could not be resolved is told so, rather than being
    // handed a blank select and left to wonder.
    const res = await extract({ line2: "Z1234567<1UTO9004115F3008155<<<<<<<<<<<<<<01" });
    expect(res.status).toBe(200);
    expect(res.body.fields.nationality).toBeNull();
    expect(res.body.unconverted).toContainEqual({
      field: "nationality",
      reason: "not a country code we recognise",
    });
  });
});

/* ── The VIZ half: the printed page ─────────────────────────────────── */
describe("POST /documents/:id/extract — the printed page (VIZ)", () => {
  async function extractWithViz(viz: Record<string, any>) {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    generateContentMock.mockResolvedValue(geminiReply({ viz_found: true, viz }));
    return request(app)
      .post(`/api/consumer/profile/documents/${doc._id}/extract`)
      .set(...auth(alice.token));
  }

  it("offers the issue date as PRINTED — never as verified", async () => {
    const res = await extractWithViz({
      surname: "SHARMA",
      givenNames: "PRIYA ANITA",
      dateOfIssue: "2020-08-16",
      documentNumber: "Z1234567",
      dateOfBirth: "1990-04-11",
      dateOfExpiry: "2030-08-15",
      sex: "F",
      nationality: "IND",
      placeOfBirth: "DELHI",
      placeOfIssue: "DELHI",
    });
    expect(res.status).toBe(200);
    // The MRZ does not carry an issue date AT ALL. This one was read off
    // the printed page, has no check digit behind it, and says so.
    expect(res.body.fields.passportIssueDate).toEqual({
      value: "2020-08-16",
      provenance: "PRINTED",
    });
    // The MRZ-backed fields are unchanged by the VIZ being present.
    expect(res.body.fields.passportNumber.provenance).toBe("VERIFIED");
    expect(res.body.mismatches).toEqual([]);
  });

  it("surfaces a disagreement between the two zones instead of hiding it", async () => {
    const res = await extractWithViz({
      surname: "SHARMA",
      givenNames: "PRIYA ANITA",
      documentNumber: "Z9999999", // the printed page disagrees with the MRZ
      dateOfBirth: "1990-04-11",
      dateOfExpiry: "2030-08-15",
      sex: "F",
      nationality: "IND",
      dateOfIssue: null,
      placeOfBirth: null,
      placeOfIssue: null,
    });
    expect(res.status).toBe(200);
    expect(res.body.mismatches).toContainEqual({
      field: "documentNumber",
      mrzValue: "Z1234567",
      vizValue: "Z9999999",
    });
    // The MRZ value is what lands in the field — it is the checked one —
    // and the disagreement rides alongside for the reader to judge. A
    // mismatch never blocks or auto-rejects.
    expect(res.body.fields.passportNumber.value).toBe("Z1234567");
  });
});

/* ═══════════════════════════════════════════════════════════════════
 * 4. FAILURES ARE 422s WITH A CATEGORY, NOT 500s
 * ═══════════════════════════════════════════════════════════════════ */
describe("POST /documents/:id/extract — failure handling", () => {
  async function failWith(mockImpl: () => any) {
    const alice = await makeConsumer("alice@example.com");
    const doc = await makePassportDoc(alice.id);
    generateContentMock.mockImplementation(mockImpl);
    return request(app)
      .post(`/api/consumer/profile/documents/${doc._id}/extract`)
      .set(...auth(alice.token));
  }

  it("UNREADABLE_DOCUMENT when no MRZ is found", async () => {
    const res = await failWith(() => ({
      text: JSON.stringify({ mrz_found: false, line1_content: null, line2: null, viz_found: false, viz: null }),
    }));
    expect(res.status).toBe(422);
    expect(res.body.category).toBe("UNREADABLE_DOCUMENT");
    expect(res.body.code).toBe("EXTRACTION_FAILED");
    expect(res.body.error).toBeTruthy();
    // One call. A stricter prompt cannot invent an MRZ that is not there,
    // so this failure must NOT spend a retry — that is the B2B engine's
    // own rule and it survives the port.
    expect(generateContentMock).toHaveBeenCalledTimes(1);
  });

  it("MALFORMED_MRZ when an MRZ is found but will not parse, after ONE retry", async () => {
    // A line 2 that is too short to be a TD3 line and cannot be repaired
    // into one. An MRZ WAS found and read — twice — so this is a
    // different situation from "no MRZ found" and gets its own category.
    const res = await failWith(() => ({
      text: JSON.stringify({
        mrz_found: true,
        line1_content: MRZ_LINE1_CONTENT,
        line2: "Z1234567<1IND900",
        viz_found: false,
        viz: null,
      }),
    }));
    expect(res.status).toBe(422);
    expect(res.body.category).toBe("MALFORMED_MRZ");
    // Exactly two: the first attempt, then the one-and-only plain retry.
    expect(generateContentMock).toHaveBeenCalledTimes(2);
  });

  it("recovers when the RETRY parses cleanly", async () => {
    let call = 0;
    const res = await failWith(() => {
      call += 1;
      // First transcription drops the trailing filler; the second is clean.
      return call === 1
        ? {
            text: JSON.stringify({
              mrz_found: true,
              line1_content: MRZ_LINE1_CONTENT,
              line2: "Z1234567<1IND900",
              viz_found: false,
              viz: null,
            }),
          }
        : geminiReply();
    });
    expect(res.status).toBe(200);
    expect(res.body.fields.passportNumber.value).toBe("Z1234567");
    expect(generateContentMock).toHaveBeenCalledTimes(2);
  });

  it("SERVICE_ERROR — and still a 422, not a 500 — when the reader itself throws", async () => {
    const res = await failWith(() => {
      throw new Error("the model exploded");
    });
    // The distinction that matters to the person waiting: this one is NOT
    // their document's fault, and the copy must not imply that it is.
    expect(res.status).toBe(422);
    expect(res.body.category).toBe("SERVICE_ERROR");
    // Never a 500. A badly-lit passport must not page an on-call engineer,
    // and must not show someone "Internal Server Error" about their
    // passport.
    expect(res.status).not.toBe(500);
  });

  it("refuses a document that is not a passport", async () => {
    const alice = await makeConsumer("alice@example.com");
    const bankStatement = await makePassportDoc(alice.id, "BANK_STATEMENT");
    generateContentMock.mockResolvedValue(geminiReply());

    const res = await request(app)
      .post(`/api/consumer/profile/documents/${bankStatement._id}/extract`)
      .set(...auth(alice.token));

    expect(res.status).toBe(400);
    expect(res.body.code).toBe("NOT_A_PASSPORT");
    // A bank statement is never sent to the passport reader — the gate is
    // before the call, not a filter on its output.
    expect(generateContentMock).not.toHaveBeenCalled();
  });

  it("accepts the LEGACY passport code as well as the catalogue one", async () => {
    // The passport has two live codes. Comparing against either one alone
    // silently skips the other — the 2026-08-08 bug. isPassportDocCode
    // resolves both, and this asserts the route actually uses it.
    const alice = await makeConsumer("alice@example.com");
    const legacy = await makePassportDoc(alice.id, "DOC-01");
    generateContentMock.mockResolvedValue(geminiReply());

    const res = await request(app)
      .post(`/api/consumer/profile/documents/${legacy._id}/extract`)
      .set(...auth(alice.token));

    expect(res.status).toBe(200);
    expect(res.body.fields.passportNumber.value).toBe("Z1234567");
  });
});
