// apps/backend/src/scripts/report-billing-own-scope-coverage.ts
//
// READ-ONLY report for scope OWN on Invoices / Credit Notes. Writes nothing.
//
// Under scope OWN a Plumtrips staff member sees an invoice when it carries a
// booking they created, or they generated it. "Created" = ManualBooking.createdBy
// (String user id), falling back to ManualBooking.bookedBy when createdBy is
// absent (Excel import / import-from-SBT set only bookedBy). This report shows
// how reliably that is filled on bookings that are on invoices:
//
//   A. Invoiced bookings: with createdBy / bookedBy-only / neither, by source,
//      createdBy ≠ bookedBy, and creators that are system identities.
//   B. Per creator: invoiced bookings, invoices they would see under OWN.
//   C. Invoices no staff OWN user would see (every booking by a system id or
//      unknown user, and not generated by staff).
//   D. Invoice lines whose bookingRef matches no booking on the invoice — no
//      OWN user can credit those lines.
//   E. Who holds scope OWN today on invoices / creditnotes / manualBookings.
//
//   $env:MONGO_URI = Read-Host "MONGO_URI"
//   npx tsx src/scripts/report-billing-own-scope-coverage.ts --expect-db=<db>
import "dotenv/config";
import mongoose from "mongoose";

const s = (v: unknown) => (v === undefined || v === null ? "" : String(v));
const isOid = (v: string) => /^[a-f0-9]{24}$/i.test(v);

async function main() {
  const args = process.argv.slice(2);
  const expectDb = args.find((a) => a.startsWith("--expect-db="))?.split("=")[1];
  const uri = process.env.MONGO_URI;
  if (!uri) throw new Error("MONGO_URI is not set");
  await mongoose.connect(uri, { autoIndex: false, autoCreate: false });
  const db = mongoose.connection.name;
  if (!expectDb) throw new Error(`REFUSING: --expect-db=<name> is required (connected db: "${db}").`);
  if (expectDb !== db) throw new Error(`REFUSING: --expect-db="${expectDb}" but connected db is "${db}".`);
  const col = (n: string) => mongoose.connection.collection(n);
  console.log(`db ${db} · READ-ONLY report · ${new Date().toISOString()}\n`);

  const invoices = await col("invoices")
    .find({ isDemo: { $ne: true } }, { projection: { invoiceNo: 1, status: 1, bookingIds: 1, createdBy: 1, lineItems: 1 } })
    .toArray();
  const bookingIds = [...new Set(invoices.flatMap((i: any) => (i.bookingIds || []).map(s)))].filter(isOid);
  const bookings = await col("manualbookings")
    .find({ _id: { $in: bookingIds.map((id) => new mongoose.Types.ObjectId(id)) } },
      { projection: { bookingRef: 1, source: 1, createdBy: 1, createdByEmail: 1, bookedBy: 1 } })
    .toArray();
  const bookingById = new Map(bookings.map((b: any) => [s(b._id), b]));
  const creatorOf = (b: any) => s(b?.createdBy) || s(b?.bookedBy);

  const userIds = new Set<string>();
  for (const b of bookings as any[]) { if (isOid(creatorOf(b))) userIds.add(creatorOf(b)); if (isOid(s(b.bookedBy))) userIds.add(s(b.bookedBy)); }
  for (const i of invoices as any[]) if (isOid(s(i.createdBy))) userIds.add(s(i.createdBy));
  const users = await col("users")
    .find({ _id: { $in: [...userIds].map((id) => new mongoose.Types.ObjectId(id)) } },
      { projection: { email: 1, name: 1, firstName: 1, lastName: 1, roles: 1, workspaceId: 1, status: 1 } })
    .toArray();
  const userById = new Map(users.map((u: any) => [s(u._id), u]));
  const isSystem = (u: any) => /system|intake|d2c|noreply|no-reply/i.test(`${s(u?.email)} ${s(u?.name)}`);
  const label = (id: string) => {
    const u: any = userById.get(id);
    if (!u) return `${id || "(none)"} (no such user)`;
    const nm = s(u.name) || `${s(u.firstName)} ${s(u.lastName)}`.trim();
    return `${s(u.email)}${nm ? ` · ${nm}` : ""}${isSystem(u) ? " [SYSTEM]" : ""}${u.status && u.status !== "active" ? ` [${u.status}]` : ""}`;
  };

  /* ── A. coverage on invoiced bookings ─────────────────────────────── */
  let withCreatedBy = 0, bookedByOnly = 0, neither = 0, disagree = 0, unknownUser = 0, systemCreator = 0;
  const bySource = new Map<string, { total: number; createdBy: number; bookedByOnly: number }>();
  for (const b of bookings as any[]) {
    const src = s(b.source) || "(unset)";
    const row = bySource.get(src) || { total: 0, createdBy: 0, bookedByOnly: 0 };
    row.total++;
    if (s(b.createdBy)) { withCreatedBy++; row.createdBy++; }
    else if (s(b.bookedBy)) { bookedByOnly++; row.bookedByOnly++; }
    else neither++;
    bySource.set(src, row);
    if (s(b.createdBy) && s(b.bookedBy) && s(b.createdBy) !== s(b.bookedBy)) disagree++;
    const c = creatorOf(b);
    const u = userById.get(c);
    if (!u) unknownUser++;
    else if (isSystem(u)) systemCreator++;
  }
  console.log(`A. invoices (non-demo): ${invoices.length} · bookings on them: ${bookingIds.length} (found ${bookings.length}, missing ${bookingIds.length - bookings.length})`);
  console.log(`   creator from createdBy: ${withCreatedBy} · from bookedBy only: ${bookedByOnly} · neither: ${neither}`);
  console.log(`   createdBy ≠ bookedBy: ${disagree} · creator is not a user: ${unknownUser} · creator is a system identity: ${systemCreator}`);
  console.log("   by source (total / createdBy / bookedBy-only):");
  for (const [src, r] of [...bySource.entries()].sort()) console.log(`     ${src.padEnd(12)} ${r.total} / ${r.createdBy} / ${r.bookedByOnly}`);

  /* ── B. per creator ─────────────────────────────────────────────────── */
  const perCreator = new Map<string, { bookings: number; invoices: Set<string> }>();
  const touch = (id: string) => {
    if (!perCreator.has(id)) perCreator.set(id, { bookings: 0, invoices: new Set() });
    return perCreator.get(id)!;
  };
  for (const b of bookings as any[]) touch(creatorOf(b)).bookings++;
  for (const inv of invoices as any[]) {
    const seen = new Set<string>();
    for (const id of (inv.bookingIds || []).map(s)) {
      const c = creatorOf(bookingById.get(id));
      if (c) seen.add(c);
    }
    if (s(inv.createdBy)) seen.add(s(inv.createdBy));
    for (const c of seen) touch(c).invoices.add(s(inv._id));
  }
  console.log(`\nB. per creator — invoiced bookings created · invoices visible under OWN (≥1 own booking or generated by them)`);
  for (const [id, r] of [...perCreator.entries()].sort((a, b) => b[1].invoices.size - a[1].invoices.size)) {
    console.log(`   ${String(r.bookings).padStart(5)} · ${String(r.invoices.size).padStart(5)}  ${label(id)}`);
  }

  /* ── C. invoices no staff OWN user would see ────────────────────────── */
  const orphan: string[] = [];
  for (const inv of invoices as any[]) {
    const people = [
      ...(inv.bookingIds || []).map((id: any) => creatorOf(bookingById.get(s(id)))),
      s(inv.createdBy),
    ].filter((id) => { const u = userById.get(id); return u && !isSystem(u); });
    if (!people.length) orphan.push(`${s(inv.invoiceNo)} (${s(inv.status)})`);
  }
  console.log(`\nC. invoices with no staff creator or generator (only scope ALL sees them): ${orphan.length}`);
  for (const o of orphan.slice(0, 50)) console.log(`   ${o}`);
  if (orphan.length > 50) console.log(`   … ${orphan.length - 50} more`);

  /* ── D. lines no OWN user can credit ────────────────────────────────── */
  let unmatched = 0;
  const unmatchedSamples: string[] = [];
  for (const inv of invoices as any[]) {
    const refs = new Set((inv.bookingIds || []).map((id: any) => s(bookingById.get(s(id))?.bookingRef)).filter(Boolean));
    for (const li of (inv.lineItems || []) as any[]) {
      const lineRefs = s(li?.bookingRef).split(",").map((r) => r.trim()).filter(Boolean);
      if (!lineRefs.length || lineRefs.some((r) => !refs.has(r))) {
        unmatched++;
        if (unmatchedSamples.length < 20) unmatchedSamples.push(`${s(inv.invoiceNo)}: "${s(li?.description).slice(0, 50)}" ref "${s(li?.bookingRef)}"`);
      }
    }
  }
  console.log(`\nD. invoice lines whose bookingRef matches no booking on the invoice (OWN users cannot credit them): ${unmatched}`);
  for (const x of unmatchedSamples) console.log(`   ${x}`);

  /* ── E. scope OWN holders ───────────────────────────────────────────── */
  const perms = await col("userpermissions")
    .find({ $or: ["invoices", "creditnotes", "manualBookings"].map((m) => ({ [`modules.${m}.scope`]: "OWN", [`modules.${m}.access`]: { $nin: [null, "NONE"] } })) },
      { projection: { userId: 1, email: 1, "modules.invoices": 1, "modules.creditnotes": 1, "modules.manualBookings": 1 } })
    .toArray();
  console.log(`\nE. scope OWN holders (any of invoices / creditnotes / manualBookings): ${perms.length}`);
  for (const p of perms as any[]) {
    const m = p.modules || {};
    const f = (k: string) => (m[k] ? `${s(m[k].access)}/${s(m[k].scope)}` : "-");
    const r = perCreator.get(s(p.userId));
    console.log(`   ${s(p.email).padEnd(36)} invoices ${f("invoices").padEnd(10)} creditnotes ${f("creditnotes").padEnd(10)} manualBookings ${f("manualBookings").padEnd(10)} → sees ${r?.invoices.size ?? 0} invoices`);
  }

  await mongoose.disconnect();
}

main().catch(async (err) => {
  console.error(err?.message || err);
  await mongoose.disconnect().catch(() => {});
  process.exit(1);
});
