// apps/backend/src/utils/billingOwnScope.ts
//
// Scope OWN for Invoices and Credit Notes (Imran's decision, 2026-10-07).
//
// A Plumtrips staff member whose invoices / creditnotes grant has scope OWN
// sees and acts on billing only for the bookings THEY created:
//   • an invoice is theirs when it carries at least one booking they created,
//     or they generated it (Invoice.createdBy);
//   • a credit note is theirs when it is on one of those invoices, or they
//     created it (CreditNote.createdBy);
//   • they may invoice, and credit, only lines of bookings they created.
// Scope ALL / WORKSPACE / TEAM, Super Admin, and non-Plumtrips callers are
// untouched — billingOwnUserId() returns null for them and every caller then
// behaves exactly as before. The tenant gate (invoiceTenantClause) still
// applies on top, unchanged.
//
// WHO CREATED A BOOKING: ManualBooking.createdBy (String user id) — the field
// Manual Bookings' own OWN filter already uses — and, when that is absent,
// ManualBooking.bookedBy (required ObjectId). POST /api/admin/manual-bookings
// (incl. Admin Queue Book Now) sets both to the caller; the Excel import and
// import-from-SBT set only bookedBy (the importer). Invoices only ever contain
// ManualBookings (Invoice.bookingIds ref "ManualBooking"); SBT bookings reach
// an invoice only through import-from-SBT.
import mongoose from "mongoose";
import ManualBooking from "../models/ManualBooking.js";
import { isSuperAdmin } from "../middleware/isSuperAdmin.js";
import { isHouseCallerContext } from "./bookingAccess.js";
import { userNames, nameOrUnknown } from "../services/actorNames.js";

const isOid = (v: string) => mongoose.Types.ObjectId.isValid(v) && /^[a-f0-9]{24}$/i.test(v);

/**
 * The caller's user id when scope OWN applies to this request, else null.
 * Reads req.permissionScope, so it reflects the grant of the module the route
 * checked (invoices on invoice routes, creditnotes on credit-note routes).
 */
export function billingOwnUserId(req: any): string | null {
  if (req.permissionScope !== "OWN") return null;
  if (isSuperAdmin(req)) return null;
  const callerId = String(req.user?._id ?? req.user?.id ?? req.user?.sub ?? "");
  const house = isHouseCallerContext({
    callerId,
    customerId: req.workspace?.customerId ?? null,
    workspaceObjectId: req.workspaceObjectId,
    permissionScope: req.permissionScope,
    isSuperAdmin: false,
  });
  return house ? callerId : null;
}

/** ManualBooking clause: bookings this user created (see header). */
export function bookingCreatorClause(userId: string): Record<string, any> {
  const or: any[] = [{ createdBy: userId }];
  if (isOid(userId)) {
    or.push({ createdBy: { $in: [null, ""] }, bookedBy: new mongoose.Types.ObjectId(userId) });
  }
  return { $or: or };
}

/** The creator of one loaded booking, by the same rule as bookingCreatorClause. */
export function bookingCreatorId(b: any): string {
  return String(b?.createdBy || "") || String(b?.bookedBy || "");
}

/** Invoice clause: invoices with ≥1 booking this user created, or generated by them. */
export async function ownInvoiceClause(userId: string): Promise<Record<string, any>> {
  const ownBookingIds = await ManualBooking.distinct("_id", bookingCreatorClause(userId));
  const or: any[] = [{ bookingIds: { $in: ownBookingIds } }];
  if (isOid(userId)) or.push({ createdBy: new mongoose.Types.ObjectId(userId) });
  return { $or: or };
}

/** The same rule as ownInvoiceClause, for one loaded invoice. */
export async function invoiceOwnedBy(userId: string, invoice: any): Promise<boolean> {
  if (invoice?.createdBy && String(invoice.createdBy) === userId) return true;
  const ids = (invoice?.bookingIds ?? []).filter((id: any) => isOid(String(id)));
  if (!ids.length) return false;
  return Boolean(await ManualBooking.exists({ _id: { $in: ids }, ...bookingCreatorClause(userId) }));
}

/** Booking refs among these ids NOT created by this user (unknown ids are left to the caller). */
export async function bookingRefsNotCreatedBy(userId: string, bookingIds: unknown[]): Promise<string[]> {
  const ids = [...new Set(bookingIds.map(String))].filter(isOid).map((id) => new mongoose.Types.ObjectId(id));
  if (!ids.length) return [];
  const docs = await ManualBooking.find({ _id: { $in: ids } }).select("bookingRef createdBy bookedBy").lean();
  return (docs as any[])
    .filter((b) => bookingCreatorId(b) !== userId)
    .map((b) => b.bookingRef || String(b._id));
}

export type LineOwner = { mine: boolean; bookedBy: string };

/**
 * Who booked each line of an invoice, from this user's point of view. A line
 * names its booking(s) by bookingRef — a combined-style line lists several,
 * comma-separated — and is the user's only when EVERY booking it names was
 * created by them. A line naming no booking on the invoice is never theirs.
 * Returns a resolver keyed by the line's bookingRef string.
 */
export async function invoiceLineOwners(invoice: any, userId: string): Promise<(bookingRef: unknown) => LineOwner> {
  const ids = (invoice?.bookingIds ?? []).filter((id: any) => isOid(String(id)));
  const bookings = ids.length
    ? ((await ManualBooking.find({ _id: { $in: ids } }).select("bookingRef createdBy bookedBy").lean()) as any[])
    : [];
  const creatorByRef = new Map<string, string>();
  for (const b of bookings) if (b.bookingRef) creatorByRef.set(String(b.bookingRef), bookingCreatorId(b));
  const names = await userNames([...creatorByRef.values()]);

  return (bookingRef: unknown) => {
    const refs = String(bookingRef ?? "").split(",").map((r) => r.trim()).filter(Boolean);
    if (!refs.length) return { mine: false, bookedBy: "" };
    const creators = refs.map((r) => creatorByRef.get(r) ?? "");
    const mine = creators.every((c) => c === userId);
    const others = [...new Set(creators.filter((c) => c !== userId))];
    const bookedBy = others.map((c) => (c ? nameOrUnknown(names.get(c)) : "")).filter(Boolean).join(", ");
    return { mine, bookedBy };
  };
}

/** The refusal text for a credit-note line the user did not book. */
export function notYourLineMessage(description: string, owner: LineOwner): string {
  const who = owner.bookedBy ? `Booked by ${owner.bookedBy}` : "Not one of your bookings";
  return `"${description}": ${who} — ask finance. You can credit only lines of bookings you created.`;
}
