// Unit coverage for the pure TD3 MRZ parser (utils/mrz.ts). No network, no
// DB — parseTD3Mrz/deriveConfidence/resolveMrzDate/computeCheckDigit are
// all pure functions.
//
// The valid fixture below is ICAO 9303's own worked example (Anna Maria
// Eriksson, a Utopian passport) — every check digit here (documentNumber=6,
// dateOfBirth=2, dateOfExpiry=9, optionalData=1, composite=0) is the
// textbook value, independently re-derived by hand against the 7-3-1
// algorithm while writing these tests, not generated by calling the
// implementation under test.
import { describe, it, expect } from "vitest";
import {
  parseTD3Mrz,
  parseTD3MrzWithRepair,
  maskMrzLine,
  deriveConfidence,
  resolveMrzDate,
  computeCheckDigit,
  type MrzCheckResult,
} from "./mrz.js";

const VALID_LINE1 = "P<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<";
const VALID_LINE2 = "L898902C36UTO7408122F1204159ZE184226B<<<<<10";

describe("parseTD3Mrz — valid MRZ", () => {
  it("parses every field correctly", () => {
    const result = parseTD3Mrz(VALID_LINE1, VALID_LINE2);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.result.documentType).toBe("P");
    expect(result.result.issuingState).toBe("UTO");
    expect(result.result.surname).toBe("ERIKSSON");
    expect(result.result.givenNames).toBe("ANNA MARIA");
    expect(result.result.documentNumber).toBe("L898902C3");
    expect(result.result.nationality).toBe("UTO");
    expect(result.result.dateOfBirth).toBe("740812");
    expect(result.result.sex).toBe("F");
    expect(result.result.dateOfExpiry).toBe("120415");
  });

  it("all five check digits pass", () => {
    const result = parseTD3Mrz(VALID_LINE1, VALID_LINE2);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.result.checks).toHaveLength(5);
    for (const check of result.result.checks) {
      expect(check.passed).toBe(true);
    }
  });

  it("is tolerant of lowercase input and surrounding whitespace", () => {
    const result = parseTD3Mrz(`  ${VALID_LINE1.toLowerCase()}  `, VALID_LINE2.toLowerCase());
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.result.documentNumber).toBe("L898902C3");
    expect(result.result.checks.every((c) => c.passed)).toBe(true);
  });
});

describe("parseTD3Mrz — each check-digit failure mode", () => {
  it("flags a corrupted documentNumber check digit", () => {
    // pos9 '6' -> '5'; composite (which embeds this check char) is now
    // necessarily wrong too — a field failure implies the composite fails.
    const corrupted = VALID_LINE2.slice(0, 9) + "5" + VALID_LINE2.slice(10);
    const result = parseTD3Mrz(VALID_LINE1, corrupted);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const documentNumberCheck = result.result.checks.find((c) => c.field === "documentNumber");
    expect(documentNumberCheck?.passed).toBe(false);
  });

  it("flags a corrupted dateOfBirth check digit", () => {
    const corrupted = VALID_LINE2.slice(0, 19) + "9" + VALID_LINE2.slice(20);
    const result = parseTD3Mrz(VALID_LINE1, corrupted);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const dobCheck = result.result.checks.find((c) => c.field === "dateOfBirth");
    expect(dobCheck?.passed).toBe(false);
  });

  it("flags a corrupted dateOfExpiry check digit", () => {
    const corrupted = VALID_LINE2.slice(0, 27) + "0" + VALID_LINE2.slice(28);
    const result = parseTD3Mrz(VALID_LINE1, corrupted);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const expiryCheck = result.result.checks.find((c) => c.field === "dateOfExpiry");
    expect(expiryCheck?.passed).toBe(false);
  });

  it("flags a corrupted optionalData check digit", () => {
    const corrupted = VALID_LINE2.slice(0, 42) + "9" + VALID_LINE2.slice(43);
    const result = parseTD3Mrz(VALID_LINE1, corrupted);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const optionalCheck = result.result.checks.find((c) => c.field === "optionalData");
    expect(optionalCheck?.passed).toBe(false);
  });

  it("flags a corrupted composite check digit while every field check still passes", () => {
    // pos43 '0' -> '9' — only the composite digit itself changes, so every
    // field-level check (which doesn't depend on pos43) still passes.
    const corrupted = VALID_LINE2.slice(0, 43) + "9";
    const result = parseTD3Mrz(VALID_LINE1, corrupted);
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const composite = result.result.checks.find((c) => c.field === "composite");
    expect(composite?.passed).toBe(false);

    const fieldChecks = result.result.checks.filter((c) => c.field !== "composite");
    expect(fieldChecks.every((c) => c.passed)).toBe(true);
  });

  it("accepts a legitimately unused optional-data field ('<' check char over all-filler data)", () => {
    // Replace the 14-char optional data field with all filler and its check
    // char with '<' — ICAO 9303 explicitly allows this combination.
    const line2 =
      VALID_LINE2.slice(0, 28) + "<".repeat(14) + "<" + VALID_LINE2.slice(43);
    const result = parseTD3Mrz(VALID_LINE1, line2);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const optionalCheck = result.result.checks.find((c) => c.field === "optionalData");
    expect(optionalCheck?.passed).toBe(true);
    expect(optionalCheck?.expected).toBeNull();
  });
});

describe("parseTD3Mrz — no longer pads anything (strict exact-length parser)", () => {
  // Repair follow-up (2026-07-30): parseTD3Mrz itself is back to a strict
  // exact-length parser — recovery now lives entirely in
  // parseTD3MrzWithRepair (see the describe block below), which requires
  // check-digit validation before accepting any repaired candidate. A
  // short/long line 1 that parseTD3Mrz used to silently pad and accept
  // unconditionally is now a plain structural rejection here.
  it("rejects a line 1 short by 2 rather than padding it", () => {
    const shortLine1 = VALID_LINE1.slice(0, -2);
    expect(shortLine1).toHaveLength(42);

    const result = parseTD3Mrz(shortLine1, VALID_LINE2);
    expect(result.ok).toBe(false);
    if (!("error" in result)) throw new Error("expected an error result");
    expect(result.error.type).toBe("invalid_length");
  });

  it("rejects an over-length line 1 rather than truncating it", () => {
    const longLine1 = VALID_LINE1 + "<";
    expect(longLine1).toHaveLength(45);

    const result = parseTD3Mrz(longLine1, VALID_LINE2);
    expect(result.ok).toBe(false);
    if (!("error" in result)) throw new Error("expected an error result");
    expect(result.error.type).toBe("invalid_length");
  });

  it("rejects a short line 2 exactly as it rejects a short line 1 — both are just length errors here now", () => {
    const shortLine2 = VALID_LINE2.slice(0, -2);
    expect(shortLine2).toHaveLength(42);

    const result = parseTD3Mrz(VALID_LINE1, shortLine2);
    expect(result.ok).toBe(false);
    if (!("error" in result)) throw new Error("expected an error result");
    expect(result.error.type).toBe("invalid_length");
    expect(result.error.message).toContain("44 and 42");
  });
});

describe("parseTD3MrzWithRepair — candidate repairs, verified by check digits", () => {
  it("returns the as-received result untouched, repairedVia 'as_received', when both lines are already exactly 44", () => {
    const outcome = parseTD3MrzWithRepair(VALID_LINE1, VALID_LINE2);
    expect(outcome.repairedVia).toBe("as_received");
    expect(outcome.adjustment).toBe(0);
    expect(outcome.result.ok).toBe(true);
    if (!outcome.result.ok) return;
    expect(outcome.result.result.checks.every((c) => c.passed)).toBe(true);
  });

  it("repairs a line 1 short by 2 (dropped trailing '<' filler) and validates via check digits", () => {
    const shortLine1 = VALID_LINE1.slice(0, -2);
    const outcome = parseTD3MrzWithRepair(shortLine1, VALID_LINE2);

    expect(outcome.repairedVia).toBe("line1");
    expect(outcome.adjustment).toBe(2);
    expect(outcome.result.ok).toBe(true);
    if (!outcome.result.ok) return;
    expect(outcome.result.result.documentNumber).toBe("L898902C3");
    expect(outcome.result.result.surname).toBe("ERIKSSON");
    expect(outcome.result.result.checks.every((c) => c.passed)).toBe(true);
  });

  it("repairs a line 1 short by exactly the cap (6)", () => {
    const shortLine1 = VALID_LINE1.slice(0, -6);
    const outcome = parseTD3MrzWithRepair(shortLine1, VALID_LINE2);
    expect(outcome.repairedVia).toBe("line1");
    expect(outcome.adjustment).toBe(6);
    expect(outcome.result.ok).toBe(true);
  });

  it("repairs an over-length line 1 whose excess is pure filler", () => {
    const longLine1 = VALID_LINE1 + "<<<"; // 47 chars, 3 extra "<"
    const outcome = parseTD3MrzWithRepair(longLine1, VALID_LINE2);
    expect(outcome.repairedVia).toBe("line1");
    expect(outcome.adjustment).toBe(3);
    expect(outcome.result.ok).toBe(true);
    if (!outcome.result.ok) return;
    expect(outcome.result.result.checks.every((c) => c.passed)).toBe(true);
  });

  // Task brief's two required cases: line 2 too long by 1, and by 4 —
  // dropped/duplicated "<" filler WITHIN the optional-data run, the last
  // two characters (optional-data check + composite check) always taken
  // verbatim from the end of the raw line regardless of the miscount.
  it("line 2 at 45 (one extra filler char in the optional-data run) repairs and validates", () => {
    const line2Plus1 = VALID_LINE2.slice(0, 41) + "<" + VALID_LINE2.slice(41);
    expect(line2Plus1).toHaveLength(45);

    const outcome = parseTD3MrzWithRepair(VALID_LINE1, line2Plus1);
    expect(outcome.repairedVia).toBe("line2");
    expect(outcome.adjustment).toBe(1);
    expect(outcome.result.ok).toBe(true);
    if (!outcome.result.ok) return;
    expect(outcome.result.result.documentNumber).toBe("L898902C3");
    expect(outcome.result.result.checks.every((c) => c.passed)).toBe(true);
  });

  it("line 2 at 48 (four extra filler chars) repairs and validates", () => {
    const line2Plus4 = VALID_LINE2.slice(0, 41) + "<".repeat(4) + VALID_LINE2.slice(41);
    expect(line2Plus4).toHaveLength(48);

    const outcome = parseTD3MrzWithRepair(VALID_LINE1, line2Plus4);
    expect(outcome.repairedVia).toBe("line2");
    expect(outcome.adjustment).toBe(4);
    expect(outcome.result.ok).toBe(true);
    if (!outcome.result.ok) return;
    expect(outcome.result.result.checks.every((c) => c.passed)).toBe(true);
  });

  it("recovers the diagnosed real case — line 1 short by 1 AND line 2 long by 1 at the same time", () => {
    const shortLine1 = VALID_LINE1.slice(0, -1); // 43 chars
    const longLine2 = VALID_LINE2.slice(0, 41) + "<" + VALID_LINE2.slice(41); // 45 chars
    expect(shortLine1).toHaveLength(43);
    expect(longLine2).toHaveLength(45);

    const outcome = parseTD3MrzWithRepair(shortLine1, longLine2);
    expect(outcome.repairedVia).toBe("both");
    expect(outcome.adjustment).toBe(2); // 1 added to line 1 + 1 removed from line 2
    expect(outcome.result.ok).toBe(true);
    if (!outcome.result.ok) return;
    expect(outcome.result.result.checks.every((c) => c.passed)).toBe(true);
  });

  it("rejects a line-1 repair that would have to remove a real character — excess isn't pure filler", () => {
    const longLine1WithRealChar = VALID_LINE1 + "A"; // 45 chars, the extra char is data-shaped, not "<"
    const outcome = parseTD3MrzWithRepair(longLine1WithRealChar, VALID_LINE2);
    expect(outcome.repairedVia).toBeNull();
    expect(outcome.result.ok).toBe(false);
  });

  it("a fabricated line-2 candidate that WOULD alter data is rejected by the check-digit gate, not silently accepted", () => {
    // The guessed optional-data run here contains a real (non-"<") character
    // ("X") ahead of the trailing filler, which repairLine2OptionalData's
    // own "content <= 14 chars" heuristic can't structurally distinguish
    // from legitimate content — so it DOES build this candidate. What
    // actually rejects it is that the fabricated optional-data value no
    // longer matches the check digit computed for the true value: five
    // passing check digits on a wrongly-repaired string is not reachable by
    // chance, so this proves the checksum gate is the real safety net, not
    // just the structural heuristics.
    const withStrayChar = VALID_LINE2.slice(0, 41) + "X" + VALID_LINE2.slice(41);
    expect(withStrayChar).toHaveLength(45);

    const outcome = parseTD3MrzWithRepair(VALID_LINE1, withStrayChar);
    expect(outcome.repairedVia).toBeNull();
    expect(outcome.result.ok).toBe(false);
  });

  it("a corrupted data/check character on an already-44-length MRZ is never rescued", () => {
    // Composite check digit corrupted — both lines are already exactly 44,
    // so no length-based candidate is even generated; repair has nothing to
    // offer here and must not paper over a genuine checksum failure.
    const corruptedLine2 = VALID_LINE2.slice(0, 43) + "9";
    const outcome = parseTD3MrzWithRepair(VALID_LINE1, corruptedLine2);

    expect(outcome.repairedVia).toBeNull();
    expect(outcome.result.ok).toBe(true); // structurally valid — parseTD3Mrz doesn't reject on a failed check digit
    if (!outcome.result.ok) return;
    const composite = outcome.result.result.checks.find((c) => c.field === "composite");
    expect(composite?.passed).toBe(false); // still reported as failed, not silently fixed
  });

  it("fails beyond the adjustment cap — line 1 short by 7", () => {
    const tooShortLine1 = VALID_LINE1.slice(0, -7);
    expect(tooShortLine1).toHaveLength(37);

    const outcome = parseTD3MrzWithRepair(tooShortLine1, VALID_LINE2);
    const { result } = outcome;
    expect(outcome.repairedVia).toBeNull();
    expect(result.ok).toBe(false);
    // "error" in result, not !result.ok — see mrz.ts's own narrowing note
    // (strictNullChecks:false fails to narrow a boolean-literal
    // discriminated union into its false branch; "in" narrowing works both
    // ways).
    if (!("error" in result)) throw new Error("expected an error result");
    expect(result.error.type).toBe("invalid_length");
  });

  it("fails beyond the adjustment cap — line 2 off by 7", () => {
    const tooLongLine2 = VALID_LINE2.slice(0, 41) + "<".repeat(7) + VALID_LINE2.slice(41);
    expect(tooLongLine2).toHaveLength(51);

    const outcome = parseTD3MrzWithRepair(VALID_LINE1, tooLongLine2);
    expect(outcome.repairedVia).toBeNull();
    expect(outcome.result.ok).toBe(false);
  });
});

describe("maskMrzLine — structure without data, for logging", () => {
  it("replaces every alphanumeric with X and keeps every '<' exactly in place", () => {
    const input = "P<INDTESTCASE<<ANANYA<<<";
    const expected = "X" + "<" + "X".repeat(11) + "<<" + "X".repeat(6) + "<<<";
    expect(maskMrzLine(input)).toBe(expected);
  });

  it("masks a full valid line 1/line 2, preserving length and every '<' position, leaking no real character", () => {
    const maskedLine1 = maskMrzLine(VALID_LINE1);
    const maskedLine2 = maskMrzLine(VALID_LINE2);

    expect(maskedLine1).toHaveLength(VALID_LINE1.length);
    expect(maskedLine2).toHaveLength(VALID_LINE2.length);
    expect(/^[X<]+$/.test(maskedLine1)).toBe(true);
    expect(/^[X<]+$/.test(maskedLine2)).toBe(true);
    // Every "<" position survives unchanged.
    for (let i = 0; i < VALID_LINE1.length; i++) {
      if (VALID_LINE1[i] === "<") expect(maskedLine1[i]).toBe("<");
    }
    // No original alphanumeric (e.g. the passport number) appears anywhere.
    expect(maskedLine2).not.toContain("L898902C3");
  });

  it("returns an empty string for empty/null-ish input rather than throwing", () => {
    expect(maskMrzLine("")).toBe("");
  });
});

describe("parseTD3Mrz — malformed input", () => {
  // Narrowed via "error" in result rather than `if (result.ok) return;` —
  // this repo's tsconfig runs with strictNullChecks:false, under which TS
  // fails to narrow a boolean-literal ("ok: true" | "ok: false")
  // discriminated union into its false branch (confirmed via isolated
  // repro); "in" narrowing is unaffected and works both ways.
  it("rejects lines that are not exactly 44 characters", () => {
    // line 2 here, not line 1 — a short line 1 within LINE1_PAD_TOLERANCE is
    // now recoverable filler loss, not malformed input; see the dedicated
    // "line 1 filler-padding tolerance" describe block above for that case.
    const result = parseTD3Mrz(VALID_LINE1, VALID_LINE2.slice(0, 40));
    expect(result.ok).toBe(false);
    if (!("error" in result)) throw new Error("expected an error result");
    expect(result.error.type).toBe("invalid_length");
  });

  it("rejects a disallowed character set", () => {
    const badLine1 = "P#UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<";
    const result = parseTD3Mrz(badLine1, VALID_LINE2);
    expect(result.ok).toBe(false);
    if (!("error" in result)) throw new Error("expected an error result");
    expect(result.error.type).toBe("invalid_charset");
  });

  it("rejects a non-passport document type", () => {
    const idCardLine1 = "I<UTOERIKSSON<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<";
    const result = parseTD3Mrz(idCardLine1, VALID_LINE2);
    expect(result.ok).toBe(false);
    if (!("error" in result)) throw new Error("expected an error result");
    expect(result.error.type).toBe("invalid_document_type");
  });

  it("rejects empty input without throwing", () => {
    const result = parseTD3Mrz("", "");
    expect(result.ok).toBe(false);
  });
});

describe("computeCheckDigit — 7-3-1 weighting", () => {
  it("matches the known ICAO example values", () => {
    expect(computeCheckDigit("L898902C3")).toBe(6);
    expect(computeCheckDigit("740812")).toBe(2);
    expect(computeCheckDigit("120415")).toBe(9);
  });

  it("treats '<' as zero-value", () => {
    expect(computeCheckDigit("<<<<<<<<<")).toBe(0);
  });
});

describe("deriveConfidence", () => {
  const passing = (field: MrzCheckResult["field"]): MrzCheckResult => ({
    field,
    expected: 0,
    actual: "0",
    passed: true,
  });
  const failing = (field: MrzCheckResult["field"]): MrzCheckResult => ({
    field,
    expected: 0,
    actual: "1",
    passed: false,
  });

  it("is high when every check digit passes", () => {
    const checks: MrzCheckResult[] = [
      passing("documentNumber"),
      passing("dateOfBirth"),
      passing("dateOfExpiry"),
      passing("optionalData"),
      passing("composite"),
    ];
    expect(deriveConfidence(checks)).toBe("high");
  });

  it("is medium when only the composite check fails", () => {
    const checks: MrzCheckResult[] = [
      passing("documentNumber"),
      passing("dateOfBirth"),
      passing("dateOfExpiry"),
      passing("optionalData"),
      failing("composite"),
    ];
    expect(deriveConfidence(checks)).toBe("medium");
  });

  it("is low when any field check digit fails, regardless of composite", () => {
    const fieldFailPassingComposite: MrzCheckResult[] = [
      failing("documentNumber"),
      passing("dateOfBirth"),
      passing("dateOfExpiry"),
      passing("optionalData"),
      passing("composite"),
    ];
    expect(deriveConfidence(fieldFailPassingComposite)).toBe("low");

    const fieldFailAndCompositeFail: MrzCheckResult[] = [
      failing("documentNumber"),
      passing("dateOfBirth"),
      passing("dateOfExpiry"),
      passing("optionalData"),
      failing("composite"),
    ];
    expect(deriveConfidence(fieldFailAndCompositeFail)).toBe("low");
  });
});

describe("resolveMrzDate — century window", () => {
  const REFERENCE = new Date("2026-07-29T00:00:00Z");

  it("dob: resolves to the current century when the candidate is not in the future", () => {
    expect(resolveMrzDate("260315", "dob", REFERENCE)).toBe("2026-03-15");
  });

  it("dob: falls back a century when the candidate year would be in the future (30 -> 1930)", () => {
    expect(resolveMrzDate("300101", "dob", REFERENCE)).toBe("1930-01-01");
  });

  it("dob: falls back a century just past the boundary (27 -> 1927, one year after reference)", () => {
    expect(resolveMrzDate("270101", "dob", REFERENCE)).toBe("1927-01-01");
  });

  it("expiry: always resolves to the current century, even far in the future (30 -> 2030)", () => {
    expect(resolveMrzDate("300101", "expiry", REFERENCE)).toBe("2030-01-01");
  });

  it("expiry: resolves a past expiry within the current century normally", () => {
    expect(resolveMrzDate("200101", "expiry", REFERENCE)).toBe("2020-01-01");
  });

  it("returns null for a structurally invalid YYMMDD (wrong length)", () => {
    expect(resolveMrzDate("3001", "dob", REFERENCE)).toBeNull();
  });

  it("returns null for a non-existent calendar date", () => {
    expect(resolveMrzDate("300230", "dob", REFERENCE)).toBeNull(); // Feb 30
    expect(resolveMrzDate("301301", "expiry", REFERENCE)).toBeNull(); // month 13
  });
});
